create type "public"."friend_request_status" as enum ('pending', 'accepted', 'declined', 'blocked');

create sequence "public"."conversations_id_seq";

create sequence "public"."friend_requests_id_seq";

create sequence "public"."meeting_messages_id_seq";

create sequence "public"."messages_id_seq";

create table "public"."conversation_members" (
    "conversation_id" bigint not null,
    "user_id" bigint not null,
    "joined_at" timestamp with time zone not null default now(),
    "last_read_at" timestamp with time zone
);


alter table "public"."conversation_members" enable row level security;

create table "public"."conversations" (
    "id" bigint not null default nextval('conversations_id_seq'::regclass),
    "is_dm" boolean not null default true,
    "user1_id" bigint,
    "user2_id" bigint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."conversations" enable row level security;

create table "public"."friend_requests" (
    "id" bigint not null default nextval('friend_requests_id_seq'::regclass),
    "requester_id" bigint not null,
    "addressee_id" bigint not null,
    "status" friend_request_status not null default 'pending'::friend_request_status,
    "created_at" timestamp with time zone not null default now(),
    "responded_at" timestamp with time zone
);


alter table "public"."friend_requests" enable row level security;

create table "public"."meeting_logs" (
    "id" uuid not null default gen_random_uuid(),
    "server_id" uuid not null,
    "transcript" json not null,
    "summary" text not null,
    "started_at" timestamp with time zone not null,
    "ended_at" timestamp with time zone not null
);


alter table "public"."meeting_logs" enable row level security;

create table "public"."messages" (
    "id" bigint not null default nextval('messages_id_seq'::regclass),
    "conversation_id" bigint not null,
    "sender_id" bigint not null,
    "content" text not null,
    "created_at" timestamp with time zone not null default now(),
    "receiver_id" bigint
);


alter table "public"."messages" enable row level security;

create table "public"."profile" (
    "id" bigint generated by default as identity not null,
    "nickname" text not null,
    "bio" text,
    "accent_color" text,
    "language" text not null,
    "mic_device_id" text,
    "mic_enabled" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."profile" enable row level security;

create table "public"."rooms" (
    "id" uuid not null default gen_random_uuid(),
    "server_id" uuid not null,
    "is_active" boolean not null default false,
    "user_count" smallint not null default '0'::smallint
);


alter table "public"."rooms" enable row level security;

create table "public"."server_members" (
    "id" uuid not null default gen_random_uuid(),
    "server_id" uuid,
    "user_id" uuid,
    "joined_at" timestamp with time zone default now(),
    "left_at" timestamp with time zone,
    "role" text default 'participant'::text,
    "is_active" boolean default false
);


alter table "public"."server_members" enable row level security;

create table "public"."server_messages" (
    "id" bigint not null default nextval('meeting_messages_id_seq'::regclass),
    "meeting_id" uuid,
    "sender_id" bigint,
    "content" text not null,
    "message_type" text default 'general'::text,
    "receiver_id" bigint,
    "created_at" timestamp with time zone default now()
);


alter table "public"."server_messages" enable row level security;

create table "public"."servers" (
    "id" uuid not null default gen_random_uuid(),
    "room_name" text not null,
    "description" text,
    "host" text not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "status" text default 'waiting'::text,
    "max_participants" integer default 10,
    "is_private" boolean default false,
    "password" text
);


alter table "public"."servers" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "email" text,
    "password" text,
    "birth_year" integer,
    "birth_month" integer,
    "birth_day" integer,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid,
    "user_uuid" uuid
);


alter table "public"."users" enable row level security;

alter sequence "public"."conversations_id_seq" owned by "public"."conversations"."id";

alter sequence "public"."friend_requests_id_seq" owned by "public"."friend_requests"."id";

alter sequence "public"."meeting_messages_id_seq" owned by "public"."server_messages"."id";

alter sequence "public"."messages_id_seq" owned by "public"."messages"."id";

CREATE UNIQUE INDEX conversation_members_pkey ON public.conversation_members USING btree (conversation_id, user_id);

CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (id);

CREATE UNIQUE INDEX conversations_user_pair_idx ON public.conversations USING btree (user1_id, user2_id);

CREATE UNIQUE INDEX dm_unique_pair ON public.conversations USING btree (LEAST(user1_id, user2_id), GREATEST(user1_id, user2_id)) WHERE (is_dm = true);

CREATE UNIQUE INDEX friend_pair_unique ON public.friend_requests USING btree (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id));

CREATE UNIQUE INDEX friend_requests_pkey ON public.friend_requests USING btree (id);

CREATE UNIQUE INDEX meeting_members_meeting_id_user_id_key ON public.server_members USING btree (server_id, user_id);

CREATE UNIQUE INDEX meeting_members_pkey ON public.server_members USING btree (id);

CREATE UNIQUE INDEX meeting_messages_pkey ON public.server_messages USING btree (id);

CREATE UNIQUE INDEX meetings_pkey ON public.servers USING btree (id);

CREATE INDEX messages_conv_created_idx ON public.messages USING btree (conversation_id, created_at);

CREATE INDEX messages_conversation_id_idx ON public.messages USING btree (conversation_id);

CREATE INDEX messages_created_at_idx ON public.messages USING btree (created_at);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE INDEX messages_receiver_id_idx ON public.messages USING btree (receiver_id);

CREATE INDEX messages_sender_id_idx ON public.messages USING btree (sender_id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

CREATE UNIQUE INDEX room_logs_pkey ON public.meeting_logs USING btree (id);

CREATE UNIQUE INDEX rooms_pkey ON public.rooms USING btree (id);

CREATE UNIQUE INDEX rooms_server_id_key ON public.rooms USING btree (server_id);

CREATE UNIQUE INDEX users_auth_id_udx ON public.users USING btree (auth_id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_email_unique ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_user_uuid_udx ON public.users USING btree (user_uuid);

alter table "public"."conversation_members" add constraint "conversation_members_pkey" PRIMARY KEY using index "conversation_members_pkey";

alter table "public"."conversations" add constraint "conversations_pkey" PRIMARY KEY using index "conversations_pkey";

alter table "public"."friend_requests" add constraint "friend_requests_pkey" PRIMARY KEY using index "friend_requests_pkey";

alter table "public"."meeting_logs" add constraint "room_logs_pkey" PRIMARY KEY using index "room_logs_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."rooms" add constraint "rooms_pkey" PRIMARY KEY using index "rooms_pkey";

alter table "public"."server_members" add constraint "meeting_members_pkey" PRIMARY KEY using index "meeting_members_pkey";

alter table "public"."server_messages" add constraint "meeting_messages_pkey" PRIMARY KEY using index "meeting_messages_pkey";

alter table "public"."servers" add constraint "meetings_pkey" PRIMARY KEY using index "meetings_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."conversation_members" add constraint "conversation_members_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE not valid;

alter table "public"."conversation_members" validate constraint "conversation_members_conversation_id_fkey";

alter table "public"."conversation_members" add constraint "conversation_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."conversation_members" validate constraint "conversation_members_user_id_fkey";

alter table "public"."conversations" add constraint "conversations_dm_user1_id_fkey" FOREIGN KEY (user1_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."conversations" validate constraint "conversations_dm_user1_id_fkey";

alter table "public"."conversations" add constraint "conversations_dm_user2_id_fkey" FOREIGN KEY (user2_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."conversations" validate constraint "conversations_dm_user2_id_fkey";

alter table "public"."conversations" add constraint "dm_pair_present" CHECK (((is_dm = false) OR ((user1_id IS NOT NULL) AND (user2_id IS NOT NULL) AND (user1_id <> user2_id)))) not valid;

alter table "public"."conversations" validate constraint "dm_pair_present";

alter table "public"."friend_requests" add constraint "friend_no_self" CHECK ((requester_id <> addressee_id)) not valid;

alter table "public"."friend_requests" validate constraint "friend_no_self";

alter table "public"."friend_requests" add constraint "friend_requests_addressee_id_fkey" FOREIGN KEY (addressee_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."friend_requests" validate constraint "friend_requests_addressee_id_fkey";

alter table "public"."friend_requests" add constraint "friend_requests_requester_id_fkey" FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."friend_requests" validate constraint "friend_requests_requester_id_fkey";

alter table "public"."meeting_logs" add constraint "meeting_logs_server_id_fkey" FOREIGN KEY (server_id) REFERENCES servers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."meeting_logs" validate constraint "meeting_logs_server_id_fkey";

alter table "public"."messages" add constraint "messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_conversation_id_fkey";

alter table "public"."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

alter table "public"."profile" add constraint "profile_id_fkey" FOREIGN KEY (id) REFERENCES users(id) not valid;

alter table "public"."profile" validate constraint "profile_id_fkey";

alter table "public"."profile" add constraint "profile_user_fk" FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "profile_user_fk";

alter table "public"."rooms" add constraint "rooms_server_id_fkey" FOREIGN KEY (server_id) REFERENCES servers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."rooms" validate constraint "rooms_server_id_fkey";

alter table "public"."rooms" add constraint "rooms_server_id_key" UNIQUE using index "rooms_server_id_key";

alter table "public"."server_members" add constraint "meeting_members_meeting_id_user_id_key" UNIQUE using index "meeting_members_meeting_id_user_id_key";

alter table "public"."server_members" add constraint "meeting_members_role_check" CHECK ((role = ANY (ARRAY['host'::text, 'participant'::text, 'observer'::text]))) not valid;

alter table "public"."server_members" validate constraint "meeting_members_role_check";

alter table "public"."server_members" add constraint "server_members_server_id_fkey" FOREIGN KEY (server_id) REFERENCES servers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."server_members" validate constraint "server_members_server_id_fkey";

alter table "public"."server_members" add constraint "server_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."server_members" validate constraint "server_members_user_id_fkey";

alter table "public"."server_messages" add constraint "meeting_messages_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES servers(id) ON DELETE CASCADE not valid;

alter table "public"."server_messages" validate constraint "meeting_messages_meeting_id_fkey";

alter table "public"."server_messages" add constraint "meeting_messages_message_type_check" CHECK ((message_type = ANY (ARRAY['general'::text, 'private'::text, 'system'::text]))) not valid;

alter table "public"."server_messages" validate constraint "meeting_messages_message_type_check";

alter table "public"."server_messages" add constraint "meeting_messages_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE SET NULL not valid;

alter table "public"."server_messages" validate constraint "meeting_messages_receiver_id_fkey";

alter table "public"."server_messages" add constraint "meeting_messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."server_messages" validate constraint "meeting_messages_sender_id_fkey";

alter table "public"."servers" add constraint "meetings_status_check" CHECK ((status = ANY (ARRAY['waiting'::text, 'active'::text, 'ended'::text]))) not valid;

alter table "public"."servers" validate constraint "meetings_status_check";

alter table "public"."users" add constraint "users_auth_fk" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "users_auth_fk";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_user_uuid_udx" UNIQUE using index "users_user_uuid_udx";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_server_room()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
  insert into rooms (server_id)
  values (new.id);
  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION public.decrement_user_count(room_id uuid)
 RETURNS void
 LANGUAGE sql
AS $function$
  update rooms
  set user_count = greatest(user_count - 1, 0)
  where id = room_id;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_user_and_profile(target_email text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  user_id bigint;
begin
  select id into user_id from users where email = target_email limit 1;
  if user_id is not null then
    delete from friend_requests where requester_id = user_id or addressee_id = user_id;
    delete from profile where id = user_id;
    delete from users where id = user_id;
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_user_count(room_id uuid)
 RETURNS void
 LANGUAGE sql
AS $function$
  update rooms
  set user_count = user_count + 1
  where id = room_id;
$function$
;

create policy "conv_members_insert_self"
on "public"."conversation_members"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = conversation_members.user_id) AND (u.email = (auth.jwt() ->> 'email'::text))))));


create policy "conv_members_select_self"
on "public"."conversation_members"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = conversation_members.user_id) AND (u.email = (auth.jwt() ->> 'email'::text))))));


create policy "conv_select_members"
on "public"."conversations"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM (conversation_members m
     JOIN users u ON ((u.id = m.user_id)))
  WHERE ((m.conversation_id = conversations.id) AND (u.email = (auth.jwt() ->> 'email'::text))))));


create policy "conversations insert participants"
on "public"."conversations"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND ((me.id = conversations.user1_id) OR (me.id = conversations.user2_id))))));


create policy "conversations select participants"
on "public"."conversations"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND ((me.id = conversations.user1_id) OR (me.id = conversations.user2_id))))));


create policy "fr_insert_self"
on "public"."friend_requests"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.email = (auth.jwt() ->> 'email'::text)) AND (u.id = friend_requests.requester_id)))));


create policy "fr_select_self"
on "public"."friend_requests"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.email = (auth.jwt() ->> 'email'::text)) AND ((u.id = friend_requests.requester_id) OR (u.id = friend_requests.addressee_id))))));


create policy "fr_update_self"
on "public"."friend_requests"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.email = (auth.jwt() ->> 'email'::text)) AND ((u.id = friend_requests.requester_id) OR (u.id = friend_requests.addressee_id))))))
with check (true);


create policy "friend delete pair"
on "public"."friend_requests"
as permissive
for delete
to authenticated
using ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND ((me.id = friend_requests.requester_id) OR (me.id = friend_requests.addressee_id))))));


create policy "friend insert self"
on "public"."friend_requests"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND (me.id = friend_requests.requester_id)))));


create policy "friend select self"
on "public"."friend_requests"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND ((me.id = friend_requests.requester_id) OR (me.id = friend_requests.addressee_id))))));


create policy "Server members can all"
on "public"."meeting_logs"
as permissive
for all
to authenticated
using ((EXISTS ( SELECT 1
   FROM server_members sm
  WHERE ((sm.server_id = meeting_logs.server_id) AND (sm.user_id = auth.uid())))));


create policy "dm read by email"
on "public"."messages"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.email = auth.email()) AND ((u.id = messages.sender_id) OR (u.id = messages.receiver_id))))));


create policy "messages insert self sender"
on "public"."messages"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND (me.id = messages.sender_id)))));


create policy "messages insert self"
on "public"."messages"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND (me.id = messages.sender_id)))));


create policy "messages select participants"
on "public"."messages"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users me
  WHERE ((me.user_uuid = auth.uid()) AND ((me.id = messages.sender_id) OR (me.id = messages.receiver_id))))));


create policy "msg_insert_members"
on "public"."messages"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM (conversation_members m
     JOIN users u ON ((u.id = m.user_id)))
  WHERE ((m.conversation_id = messages.conversation_id) AND (u.email = (auth.jwt() ->> 'email'::text)) AND (m.user_id = messages.sender_id)))));


create policy "msg_select_members"
on "public"."messages"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM (conversation_members m
     JOIN users u ON ((u.id = m.user_id)))
  WHERE ((m.conversation_id = messages.conversation_id) AND (u.email = (auth.jwt() ->> 'email'::text))))));


create policy "profile insert own"
on "public"."profile"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.user_uuid = auth.uid()) AND (u.id = profile.id)))));


create policy "profile select self or friends"
on "public"."profile"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.user_uuid = auth.uid()) AND (u.id = profile.id)))) OR (EXISTS ( SELECT 1
   FROM (users me
     JOIN friend_requests fr ON (((fr.status = 'accepted'::friend_request_status) AND (((fr.requester_id = me.id) AND (fr.addressee_id = profile.id)) OR ((fr.addressee_id = me.id) AND (fr.requester_id = profile.id))))))
  WHERE (me.user_uuid = auth.uid())))));


create policy "profile self rw"
on "public"."profile"
as permissive
for all
to public
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.auth_id = auth.uid())))));


create policy "profile update own"
on "public"."profile"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.user_uuid = auth.uid()) AND (u.id = profile.id)))))
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.user_uuid = auth.uid()) AND (u.id = profile.id)))));


create policy "profile upsert own"
on "public"."profile"
as permissive
for insert
to authenticated
with check ((id IN ( SELECT users.id
   FROM users
  WHERE (users.user_uuid = auth.uid()))));


create policy "profile: insert own"
on "public"."profile"
as permissive
for insert
to authenticated
with check ((id IN ( SELECT users.id
   FROM users
  WHERE (users.user_uuid = auth.uid()))));


create policy "profile: select own"
on "public"."profile"
as permissive
for select
to authenticated
using ((id IN ( SELECT users.id
   FROM users
  WHERE (users.user_uuid = auth.uid()))));


create policy "profile: update own"
on "public"."profile"
as permissive
for update
to authenticated
using ((id IN ( SELECT users.id
   FROM users
  WHERE (users.user_uuid = auth.uid()))))
with check ((id IN ( SELECT users.id
   FROM users
  WHERE (users.user_uuid = auth.uid()))));


create policy "profile_insert_owner"
on "public"."profile"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.user_uuid = auth.uid())))));


create policy "profile_insert_self"
on "public"."profile"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.email = (auth.jwt() ->> 'email'::text))))));


create policy "profile_owner_all"
on "public"."profile"
as permissive
for all
to authenticated
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.email = auth.email())))))
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.email = auth.email())))));


create policy "profile_select_owner"
on "public"."profile"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.user_uuid = auth.uid())))));


create policy "profile_update_owner"
on "public"."profile"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.user_uuid = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = profile.id) AND (u.user_uuid = auth.uid())))));


create policy "Users can select rooms if they are members of the server"
on "public"."rooms"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM server_members members
  WHERE ((members.server_id = rooms.server_id) AND (members.user_id = auth.uid())))));


create policy "server_members_delete_policy"
on "public"."server_members"
as permissive
for delete
to authenticated
using ((user_id = auth.uid()));


create policy "server_members_insert_policy"
on "public"."server_members"
as permissive
for insert
to authenticated
with check ((user_id = auth.uid()));


create policy "server_members_select_policy"
on "public"."server_members"
as permissive
for select
to authenticated
using (true);


create policy "server_members_update_policy"
on "public"."server_members"
as permissive
for update
to authenticated
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));


create policy "Users can insert server messages"
on "public"."server_messages"
as permissive
for insert
to public
with check ((sender_id = ( SELECT users.id
   FROM users
  WHERE (users.email = (auth.jwt() ->> 'email'::text)))));


create policy "Users can view server messages"
on "public"."server_messages"
as permissive
for select
to public
using (true);


create policy "server_messages_insert_policy"
on "public"."server_messages"
as permissive
for insert
to authenticated
with check (((sender_id = ( SELECT users.id
   FROM users
  WHERE (users.user_uuid = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM server_members sm
  WHERE ((sm.server_id = server_messages.meeting_id) AND (sm.user_id = auth.uid()))))));


create policy "server_messages_select_policy"
on "public"."server_messages"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM server_members sm
  WHERE ((sm.server_id = server_messages.meeting_id) AND (sm.user_id = auth.uid())))));


create policy "servers_delete_policy"
on "public"."servers"
as permissive
for delete
to authenticated
using ((host = (auth.uid())::text));


create policy "servers_insert_policy"
on "public"."servers"
as permissive
for insert
to authenticated
with check ((host = (auth.uid())::text));


create policy "servers_select_policy"
on "public"."servers"
as permissive
for select
to authenticated
using (true);


create policy "servers_update_policy"
on "public"."servers"
as permissive
for update
to authenticated
using ((host = (auth.uid())::text))
with check ((host = (auth.uid())::text));


create policy "users insert own"
on "public"."users"
as permissive
for insert
to authenticated
with check ((user_uuid = auth.uid()));


create policy "users select own"
on "public"."users"
as permissive
for select
to authenticated
using (((user_uuid = auth.uid()) OR (email = auth.email())));


create policy "users self delete"
on "public"."users"
as permissive
for delete
to public
using ((auth.uid() = auth_id));


create policy "users update own"
on "public"."users"
as permissive
for update
to authenticated
using (((user_uuid = auth.uid()) OR ((user_uuid IS NULL) AND (email = auth.email()))))
with check ((user_uuid = auth.uid()));


create policy "users: insert own"
on "public"."users"
as permissive
for insert
to authenticated
with check ((user_uuid = auth.uid()));


create policy "users: select own"
on "public"."users"
as permissive
for select
to authenticated
using ((user_uuid = auth.uid()));


create policy "users: update own"
on "public"."users"
as permissive
for update
to authenticated
using ((user_uuid = auth.uid()))
with check ((user_uuid = auth.uid()));


create policy "users_insert_self"
on "public"."users"
as permissive
for insert
to authenticated
with check ((user_uuid = auth.uid()));


create policy "users_search_minimal"
on "public"."users"
as permissive
for select
to authenticated
using (true);


create policy "users_select_self"
on "public"."users"
as permissive
for select
to authenticated
using ((user_uuid = auth.uid()));


create policy "users_update_self"
on "public"."users"
as permissive
for update
to authenticated
using ((user_uuid = auth.uid()))
with check ((user_uuid = auth.uid()));


CREATE TRIGGER after_server_insert AFTER INSERT ON public.servers FOR EACH ROW EXECUTE FUNCTION create_server_room();



